USE Minions2;

CREATE TABLE Minions
(
Id INT NOT NULL PRIMARY KEY IDENTITY(1,1),
Name NVARCHAR(30) NOT NULL,
Age INT NOT NULL,
)

CREATE TABLE Towns
(
Id INT NOT NULL PRIMARY KEY IDENTITY(1,1),
Name NVARCHAR(30) NOT NULL,
)